export const MESSAGES = {
  WELCOME_BACK: 'Welcome back',
  SIGNUP_PROMPT: "Don't have an account?",
  INVALID_EMAIL_FORMAT: 'Invalid email format',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_REQUIRED: 'Password is required',
  RECAPTCHA_ERROR: 'Please complete the i am not a robot to proceed.',
  INVALID_EMAIL_PASSWORD: 'Invalid email or password. Please try again.',
  UNEXPECTED_ERROR: 'An unexpected error occurred. Please try again later.',
  NETWORK_ERROR: 'Unable to connect to the server. Please check your network connection.',
  SIGNUP_LINK: 'Sign up',
  LOGIN_LABEL: 'Login',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'example@example.com',
  PASSWORD_LABEL: 'Password',
};